优化路径信息

diff --git a/builder/function b/builder/function
--- a/builder/function
+++ b/builder/function
@@ -1,7 +1,7 @@
 
 wk__error() {
 
-    echo Failed: $@; exit 1
+    echo "Failed: $@"; exit 1
 
 }
 
